source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# User configuration
if [ `uname` = "Darwin" ]; then
    # for gnu
    path=(
        /usr/local/opt/gnu-sed/libexec/gnubin
        /usr/local/opt/coreutils/libexec/gnubin
        $path
    )
    manpath+=(
        /usr/local/opt/gnu-sed/libexec/gnuman
        /usr/local/opt/coreutils/libexec/gnuman
    )
    fpath=(/usr/local/share/zsh-completions $fpath)
    function o {
        if [ -n "$*" ]; then
            open "$*"
        else
            open .
        fi
    }
    hash -d ctf="$HOME/Desktop/work/workspace/ctf/"
    hash -d des="$HOME/Desktop/"
fi

path+=(
    /usr/local/bin
    /usr/local/sbin
    ~/bin
)
# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"

pyenv() {
    eval "$(command pyenv init -)"
    pyenv "$@"
}

# rvm
#[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# for ls color
eval `dircolors ${HOME}/.dotfiles/config/dircolors.256dark`

bindkey '^V' history-incremental-search-forward

# alias
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias grep="grep --color"
alias ll="ls --color=auto -lFah"
alias la="ls --color=auto -a"
alias ls="ls --color=auto -GF"
alias sl="ls --color=auto -GF"
alias cls="printf \"\033c\""

source ~/.dotfiles/config/zsh/autojump.zsh

# brew
