source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# User configuration
if [ `uname` = "Darwin" ]; then
    # for gnu
    path=(
        /usr/local/opt/gnu-sed/libexec/gnubin
        /usr/local/opt/coreutils/libexec/gnubin
        $path
    )
    manpath+=(
        /usr/local/opt/gnu-sed/libexec/gnuman
        /usr/local/opt/coreutils/libexec/gnuman
    )
    fpath=(/usr/local/share/zsh-completions $fpath)
    function o {
        if [ -n "$*" ]; then
            open "$*"
        else
            open .
        fi
    }
    hash -d ctf="$HOME/Desktop/work/workspace/ctf/"
    hash -d des="$HOME/Desktop/"
fi

path+=(
    /usr/local/bin
    /usr/local/sbin
    ~/bin
)
# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# for ls color
eval `dircolors ${HOME}/.dotfiles/config/dircolors.256dark`

bindkey '^V' history-incremental-search-forward

# alias
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias grep="grep --color"
alias ll="ls --color=auto -lFah"
alias la="ls --color=auto -a"
alias ls="ls --color=auto -GF"
alias sl="ls --color=auto -GF"
alias cls="printf \"\033c\""

if [ $commands[autojump] ]; then # check if autojump is installed
  if [ -f $HOME/.autojump/etc/profile.d/autojump.zsh ]; then # manual user-local installation
    . $HOME/.autojump/etc/profile.d/autojump.zsh
  elif [ -f $HOME/.autojump/share/autojump/autojump.zsh ]; then # another manual user-local installation
    . $HOME/.autojump/share/autojump/autojump.zsh
  elif [ -f $HOME/.nix-profile/etc/profile.d/autojump.zsh ]; then # nix installation
    . $HOME/.nix-profile/etc/profile.d/autojump.zsh
  elif [ -f /usr/share/autojump/autojump.zsh ]; then # debian and ubuntu package
    . /usr/share/autojump/autojump.zsh
  elif [ -f /etc/profile.d/autojump.zsh ]; then # manual installation
    . /etc/profile.d/autojump.zsh
  elif [ -f /etc/profile.d/autojump.sh ]; then # gentoo installation
    . /etc/profile.d/autojump.sh
  elif [ -f /usr/local/share/autojump/autojump.zsh ]; then # freebsd installation
    . /usr/local/share/autojump/autojump.zsh
  elif [ -f /opt/local/etc/profile.d/autojump.zsh ]; then # mac os x with ports
    . /opt/local/etc/profile.d/autojump.zsh
  elif [ $commands[brew] -a -f `brew --prefix`/etc/autojump.sh ]; then # mac os x with brew
    . `brew --prefix`/etc/autojump.sh
  fi
fi

# brew
